### ISSUE TITLE
Nice Layout

### ISSUE THREAD

**Issue by ChandanB** [Hassurunous/hassurunous.github.io#1]
Thats a nice layout with the written sections and the pictures. Besides the formatting that needs to be done at the top it's pretty good, and it works!. Maybe the text can pop a little more.

**Comment by Hassurunous** [comment]
Thanks for the advice! I've done a bit with it and added quite a bit! Check out [hassurunous.github.io/MetaCog](url) to see some of the new stuff I've been working on!
